// Code generated by utils/gen_embed.vsh. DO NOT EDIT.
module webdist

import v.embed_file

const dist_index_html = $embed_file('../web/dist/index.html')
const dist_webui__index_b3ul10qz_css = $embed_file('../web/dist/webui/index-B3Ul10QZ.css')
const dist_webui__index_gj443gh__js = $embed_file('../web/dist/webui/index-GJ443Gh_.js')

// get returns the embedded file for a URL path, e.g. "/webui/app.js".
pub fn get(path string) ?embed_file.EmbedFileData {
	p := if path.starts_with('/') { path } else { '/' + path }
	return match p {
		'/index.html' { dist_index_html }
		'/webui/index-B3Ul10QZ.css' { dist_webui__index_b3ul10qz_css }
		'/webui/index-GJ443Gh_.js' { dist_webui__index_gj443gh__js }
		else { return none }
	}
}

// index returns the embedded SPA entry point.
pub fn index() ?embed_file.EmbedFileData {
	return get('/index.html')
}

// paths lists every embedded file path.
pub fn paths() []string {
	return ['/index.html', '/webui/index-B3Ul10QZ.css', '/webui/index-GJ443Gh_.js']
}
