#!/usr/bin/env v

import os

// Generates webdist/embed_dist_generated.v from web/dist/** so the SPA can be
// compiled into the server binary with $embed_file. Run via `v run utils/gen_embed.vsh`.
// The generated file is committed so a fresh clone builds before any npm build.

const dist_dir = 'web/dist'
const out_file = 'webdist/embed_dist_generated.v'

fn main() {
	if !os.exists(dist_dir) {
		eprintln('error: ${dist_dir} does not exist; build the frontend first (cd web && npm run build)')
		exit(1)
	}
	os.mkdir_all('webdist') or { panic(err) }
	mut files := []string{}
	collect(dist_dir, '', mut files)
	files.sort()
	mut lines := []string{}
	lines << '// Code generated by utils/gen_embed.vsh. DO NOT EDIT.'
	lines << 'module webdist'
	lines << ''
	lines << 'import v.embed_file'
	lines << ''
	mut const_names := []string{}
	for f in files {
		cname := ('dist_' + f.replace('/', '__').replace('.', '_').replace('-', '_').replace('@', '_').replace('~', '_')).to_lower()
		lines << "const ${cname} = \$embed_file('../${dist_dir}/${f}')"
		const_names << cname
	}
	lines << ''
	lines << '// get returns the embedded file for a URL path, e.g. "/webui/app.js".'
	lines << 'pub fn get(path string) ?embed_file.EmbedFileData {'
	lines << "\tp := if path.starts_with('/') { path } else { '/' + path }"
	lines << '\treturn match p {'
	for i, f in files {
		lines << "\t\t'/${f}' { ${const_names[i]} }"
	}
	lines << '\t\telse { return none }'
	lines << '\t}'
	lines << '}'
	lines << ''
	lines << '// index returns the embedded SPA entry point.'
	lines << 'pub fn index() ?embed_file.EmbedFileData {'
	lines << "\treturn get('/index.html')"
	lines << '}'
	lines << ''
	lines << '// paths lists every embedded file path.'
	lines << 'pub fn paths() []string {'
	mut quoted := []string{cap: files.len}
	for f in files {
		quoted << "'/${f}'"
	}
	lines << '\treturn [${quoted.join(', ')}]'
	lines << '}'
	os.write_file(out_file, lines.join('\n') + '\n') or { panic(err) }
	// keep the generated file vfmt-compliant so `v fmt -verify .` stays clean
	res := os.exec(['v', 'fmt', '-w', out_file])
	if res.exit_code != 0 {
		eprintln('warning: v fmt failed on ${out_file}: ${res.output}')
	}
	println('generated ${out_file} (${files.len} files)')
}

fn collect(root string, prefix string, mut files []string) {
	entries := os.ls(root) or { return }
	for entry in entries {
		p := os.join_path(root, entry)
		rel := if prefix == '' { entry } else { prefix + '/' + entry }
		if os.is_dir(p) {
			collect(p, rel, mut files)
		} else {
			files << rel
		}
	}
}
