#!/usr/bin/env v

import os

// Generates internal/webdist/embed_dist_generated.v from web/out/** so the Next.js static
// export can be compiled into the server binary with $embed_file. Run via
// `v run scripts/gen_embed.vsh` (after `cd web && npm run build`).
// The generated file is committed so a fresh clone builds before any npm build.

const dist_dir = 'web/out'
const out_file = 'internal/webdist/embed_dist_generated.v'

fn main() {
	if !os.exists(dist_dir) {
		eprintln('error: ${dist_dir} does not exist; build the frontend first (cd web && npm run build)')
		exit(1)
	}
	os.mkdir_all('internal/webdist') or { panic(err) }
	mut files := []string{}
	collect(dist_dir, '', mut files)
	files.sort()
	if 'index.html' !in files {
		eprintln('warning: ${dist_dir}/index.html not found; did `next build` succeed?')
	}
	mut lines := []string{}
	lines << '// Code generated by scripts/gen_embed.vsh. DO NOT EDIT.'
	lines << 'module webdist'
	lines << ''
	lines << 'import os'
	lines << 'import v.embed_file'
	lines << ''
	mut const_names := []string{cap: files.len}
	mut used_names := map[string]bool{}
	for f in files {
		mut cname := 'dist_' + sanitize_ident(f)
		if used_names[cname] {
			mut i := 2
			for used_names['${cname}_${i}'] {
				i++
			}
			cname = '${cname}_${i}'
		}
		used_names[cname] = true
		const_names << cname
		lines << "const ${cname} = \$embed_file('../../${dist_dir}/${f}')"
	}
	lines << ''
	lines << '// get returns the embedded file for a URL path, e.g. "/machines.html".'
	lines << 'pub fn get(path string) ?embed_file.EmbedFileData {'
	lines << "\tp := if path.starts_with('/') { path } else { '/' + path }"
	lines << '\treturn match p {'
	for i, f in files {
		lines << "\t\t'/${f}' { ${const_names[i]} }"
	}
	lines << '\t\telse { return none }'
	lines << '\t}'
	lines << '}'
	lines << ''
	lines << '// has_file reports whether a file is embedded under the given URL path.'
	lines << 'fn has_file(path string) bool {'
	lines << '\tget(path) or { return false }'
	lines << '\treturn true'
	lines << '}'
	lines << ''
	lines << '// resolve maps a URL path to the canonical embedded path of the Next.js'
	lines << '// static export: exact file, "<path>.html" page, or "<path>/index.html".'
	lines << 'pub fn resolve(path string) ?string {'
	lines << "\tmut p := if path.starts_with('/') { path } else { '/' + path }"
	lines << "\tif p.len > 1 && p.ends_with('/') {"
	lines << '\t\tp = p[..p.len - 1]'
	lines << '\t}'
	lines << "\tif p == '/' {"
	lines << "\t\tp = '/index.html'"
	lines << '\t}'
	lines << '\tif has_file(p) {'
	lines << '\t\treturn p'
	lines << '\t}'
	lines << "\tif p.ends_with('.html') {"
	lines << '\t\treturn none'
	lines << '\t}'
	lines << "\tif has_file(p + '.html') {"
	lines << "\t\treturn p + '.html'"
	lines << '\t}'
	lines << "\tif has_file(p + '/index.html') {"
	lines << "\t\treturn p + '/index.html'"
	lines << '\t}'
	lines << '\treturn none'
	lines << '}'
	lines << ''
	lines << '// index returns the embedded app entry point.'
	lines << 'pub fn index() ?embed_file.EmbedFileData {'
	lines << "\treturn get('/index.html')"
	lines << '}'
	lines << ''
	lines << '// paths lists every embedded file path.'
	lines << 'pub fn paths() []string {'
	mut quoted := []string{cap: files.len}
	for f in files {
		quoted << "'/${f}'"
	}
	lines << '\treturn [${quoted.join(', ')}]'
	lines << '}'
	lines << ''
	lines << '// sources_present reports whether the dev-mode source files still exist'
	lines << '// on disk. Dev builds read embedded files lazily from disk; if they are'
	lines << '// gone, serving the UI must be disabled gracefully instead of crashing.'
	lines << 'pub fn sources_present() bool {'
	mut checks := []string{cap: files.len}
	for f in files {
		checks << "os.exists(@VMODROOT + '/${dist_dir}/${f}')"
	}
	lines << '\treturn ${checks.join(' && ')}'
	lines << '}'
	os.write_file(out_file, lines.join('\n') + '\n') or { panic(err) }
	// keep the generated file vfmt-compliant so `v fmt -verify .` stays clean
	res := os.exec(['v', 'fmt', '-w', out_file])
	if res.exit_code != 0 {
		eprintln('warning: v fmt failed on ${out_file}: ${res.output}')
	}
	println('generated ${out_file} (${files.len} files)')
}

fn sanitize_ident(s string) string {
	mut out := ''
	for c in s.to_lower_ascii() {
		if c.is_letter() || c.is_digit() {
			out += c.ascii_str()
		} else {
			out += '_'
		}
	}
	return out
}

fn collect(root string, prefix string, mut files []string) {
	entries := os.ls(root) or { return }
	for entry in entries {
		p := os.join_path(root, entry)
		rel := if prefix == '' { entry } else { prefix + '/' + entry }
		if os.is_dir(p) {
			collect(p, rel, mut files)
		} else {
			files << rel
		}
	}
}
